-- megafunction wizard: %DDR2 High Performance Controller v8.0%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			ddr2_deva_controller_phy
-- ============================================================
-- Generated by DDR2 High Performance Controller 8.0 [Altera, IP Toolbench 1.3.0 Build 214]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2010 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;

ENTITY ddr2_deva IS
	PORT (
		local_address	: IN STD_LOGIC_VECTOR (22 DOWNTO 0);
		local_write_req	: IN STD_LOGIC;
		local_read_req	: IN STD_LOGIC;
		local_burstbegin	: IN STD_LOGIC;
		local_wdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_be	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		local_size	: IN STD_LOGIC;
		oct_ctl_rs_value	: IN STD_LOGIC_VECTOR (13 DOWNTO 0);
		oct_ctl_rt_value	: IN STD_LOGIC_VECTOR (13 DOWNTO 0);
		global_reset_n	: IN STD_LOGIC;
		pll_ref_clk	: IN STD_LOGIC;
		soft_reset_n	: IN STD_LOGIC;
		local_ready	: OUT STD_LOGIC;
		local_rdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_rdata_valid	: OUT STD_LOGIC;
		reset_request_n	: OUT STD_LOGIC;
		mem_odt	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_cs_n	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_cke	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_addr	: OUT STD_LOGIC_VECTOR (12 DOWNTO 0);
		mem_ba	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		mem_ras_n	: OUT STD_LOGIC;
		mem_cas_n	: OUT STD_LOGIC;
		mem_we_n	: OUT STD_LOGIC;
		mem_dm	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		local_refresh_ack	: OUT STD_LOGIC;
		local_wdata_req	: OUT STD_LOGIC;
		local_init_done	: OUT STD_LOGIC;
		reset_phy_clk_n	: OUT STD_LOGIC;
		phy_clk	: OUT STD_LOGIC;
		aux_full_rate_clk	: OUT STD_LOGIC;
		aux_half_rate_clk	: OUT STD_LOGIC;
		mem_clk	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_clk_n	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dq	: INOUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		mem_dqs	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dqsn	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0)
	);
END ddr2_deva;

ARCHITECTURE SYN OF ddr2_deva IS

	SIGNAL signal_wire0	:  STD_LOGIC;
	SIGNAL signal_wire1	:  STD_LOGIC_VECTOR (5 DOWNTO 0);
	SIGNAL signal_wire2	:  STD_LOGIC;
	SIGNAL signal_wire3	:  STD_LOGIC;
	SIGNAL signal_wire4	:  STD_LOGIC;
	SIGNAL signal_wire5	:  STD_LOGIC;
	SIGNAL signal_wire6	:  STD_LOGIC_VECTOR (3 DOWNTO 0);
	SIGNAL signal_wire7	:  STD_LOGIC_VECTOR (2 DOWNTO 0);
	SIGNAL signal_wire8	:  STD_LOGIC_VECTOR (8 DOWNTO 0);
	SIGNAL signal_wire9	:  STD_LOGIC;
	SIGNAL signal_wire10	:  STD_LOGIC;
	SIGNAL signal_wire11	:  STD_LOGIC;
	SIGNAL signal_wire12	:  STD_LOGIC;

	COMPONENT ddr2_deva_controller_phy
	PORT (
		local_address	: IN STD_LOGIC_VECTOR (22 DOWNTO 0);
		local_write_req	: IN STD_LOGIC;
		local_read_req	: IN STD_LOGIC;
		local_burstbegin	: IN STD_LOGIC;
		local_wdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_be	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		local_size	: IN STD_LOGIC;
		local_refresh_req	: IN STD_LOGIC;
		oct_ctl_rs_value	: IN STD_LOGIC_VECTOR (13 DOWNTO 0);
		oct_ctl_rt_value	: IN STD_LOGIC_VECTOR (13 DOWNTO 0);
		dqs_delay_ctrl_import	: IN STD_LOGIC_VECTOR (5 DOWNTO 0);
		pll_reconfig_enable	: IN STD_LOGIC;
		pll_reconfig_write_param	: IN STD_LOGIC;
		pll_reconfig_read_param	: IN STD_LOGIC;
		pll_reconfig	: IN STD_LOGIC;
		pll_reconfig_counter_type	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		pll_reconfig_counter_param	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		pll_reconfig_data_in	: IN STD_LOGIC_VECTOR (8 DOWNTO 0);
		pll_reconfig_soft_reset_en_n	: IN STD_LOGIC;
		global_reset_n	: IN STD_LOGIC;
		local_autopch_req	: IN STD_LOGIC;
		local_powerdn_req	: IN STD_LOGIC;
		local_self_rfsh_req	: IN STD_LOGIC;
		pll_ref_clk	: IN STD_LOGIC;
		soft_reset_n	: IN STD_LOGIC;
		local_ready	: OUT STD_LOGIC;
		local_rdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_rdata_valid	: OUT STD_LOGIC;
		reset_request_n	: OUT STD_LOGIC;
		mem_odt	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_cs_n	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_cke	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_addr	: OUT STD_LOGIC_VECTOR (12 DOWNTO 0);
		mem_ba	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		mem_ras_n	: OUT STD_LOGIC;
		mem_cas_n	: OUT STD_LOGIC;
		mem_we_n	: OUT STD_LOGIC;
		mem_dm	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		local_refresh_ack	: OUT STD_LOGIC;
		local_wdata_req	: OUT STD_LOGIC;
		local_init_done	: OUT STD_LOGIC;
		reset_phy_clk_n	: OUT STD_LOGIC;
		mem_reset_n	: OUT STD_LOGIC;
		dll_reference_clk	: OUT STD_LOGIC;
		dqs_delay_ctrl_export	: OUT STD_LOGIC_VECTOR (5 DOWNTO 0);
		pll_reconfig_busy	: OUT STD_LOGIC;
		pll_reconfig_data_out	: OUT STD_LOGIC_VECTOR (8 DOWNTO 0);
		pll_reconfig_clk	: OUT STD_LOGIC;
		pll_reconfig_reset	: OUT STD_LOGIC;
		local_powerdn_ack	: OUT STD_LOGIC;
		local_self_rfsh_ack	: OUT STD_LOGIC;
		phy_clk	: OUT STD_LOGIC;
		aux_full_rate_clk	: OUT STD_LOGIC;
		aux_half_rate_clk	: OUT STD_LOGIC;
		mem_clk	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_clk_n	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dq	: INOUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		mem_dqs	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dqsn	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0)
	);

	END COMPONENT;

BEGIN
	signal_wire0  <=  '0';
	signal_wire1  <= (others => '0');
	signal_wire2  <=  '0';
	signal_wire3  <=  '0';
	signal_wire4  <=  '0';
	signal_wire5  <=  '0';
	signal_wire6  <= (others => '0');
	signal_wire7  <= (others => '0');
	signal_wire8  <= (others => '0');
	signal_wire9  <=  '0';
	signal_wire10  <=  '0';
	signal_wire11  <=  '0';
	signal_wire12  <=  '0';

	ddr2_deva_controller_phy_inst : ddr2_deva_controller_phy
	PORT MAP (
		local_address  =>  local_address,
		local_write_req  =>  local_write_req,
		local_read_req  =>  local_read_req,
		local_burstbegin  =>  local_burstbegin,
		local_ready  =>  local_ready,
		local_rdata  =>  local_rdata,
		local_rdata_valid  =>  local_rdata_valid,
		local_wdata  =>  local_wdata,
		local_be  =>  local_be,
		local_size  =>  local_size,
		reset_request_n  =>  reset_request_n,
		mem_odt  =>  mem_odt,
		mem_clk  =>  mem_clk,
		mem_clk_n  =>  mem_clk_n,
		mem_cs_n  =>  mem_cs_n,
		mem_cke  =>  mem_cke,
		mem_addr  =>  mem_addr,
		mem_ba  =>  mem_ba,
		mem_ras_n  =>  mem_ras_n,
		mem_cas_n  =>  mem_cas_n,
		mem_we_n  =>  mem_we_n,
		mem_dq  =>  mem_dq,
		mem_dqs  =>  mem_dqs,
		mem_dqsn  =>  mem_dqsn,
		mem_dm  =>  mem_dm,
		local_refresh_ack  =>  local_refresh_ack,
		local_refresh_req  =>  signal_wire0,
		local_wdata_req  =>  local_wdata_req,
		local_init_done  =>  local_init_done,
		reset_phy_clk_n  =>  reset_phy_clk_n,
		mem_reset_n  =>  open,
		oct_ctl_rs_value  =>  oct_ctl_rs_value,
		oct_ctl_rt_value  =>  oct_ctl_rt_value,
		dqs_delay_ctrl_import  =>  signal_wire1,
		dll_reference_clk  =>  open,
		dqs_delay_ctrl_export  =>  open,
		pll_reconfig_busy  =>  open,
		pll_reconfig_data_out  =>  open,
		pll_reconfig_enable  =>  signal_wire2,
		pll_reconfig_write_param  =>  signal_wire3,
		pll_reconfig_read_param  =>  signal_wire4,
		pll_reconfig  =>  signal_wire5,
		pll_reconfig_counter_type  =>  signal_wire6,
		pll_reconfig_counter_param  =>  signal_wire7,
		pll_reconfig_data_in  =>  signal_wire8,
		pll_reconfig_clk  =>  open,
		pll_reconfig_reset  =>  open,
		pll_reconfig_soft_reset_en_n  =>  signal_wire9,
		global_reset_n  =>  global_reset_n,
		local_autopch_req  =>  signal_wire10,
		local_powerdn_req  =>  signal_wire11,
		local_powerdn_ack  =>  open,
		local_self_rfsh_req  =>  signal_wire12,
		local_self_rfsh_ack  =>  open,
		pll_ref_clk  =>  pll_ref_clk,
		phy_clk  =>  phy_clk,
		aux_full_rate_clk  =>  aux_full_rate_clk,
		aux_half_rate_clk  =>  aux_half_rate_clk,
		soft_reset_n  =>  soft_reset_n
	);


END SYN;


-- =========================================================
-- DDR2 High Performance Controller Wizard Data
-- ===============================
-- DO NOT EDIT FOLLOWING DATA
-- @Altera, IP Toolbench@
-- Warning: If you modify this section, DDR2 High Performance Controller Wizard may not be able to reproduce your chosen configuration.
-- 
-- Retrieval info: <?xml version="1.0"?>
-- Retrieval info: <MEGACORE title="DDR2 SDRAM High Performance Controller"  version="8.0"  build="214"  iptb_version="1.3.0 Build 214"  format_version="120" >
-- Retrieval info:  <NETLIST_SECTION class="altera.ipbu.flowbase.netlist.model.DDRControllerMVCModel"  active_core="ddr2_deva_controller_phy" >
-- Retrieval info:   <STATIC_SECTION>
-- Retrieval info:    <PRIVATES>
-- Retrieval info:     <NAMESPACE name = "parameterization">
-- Retrieval info:      <PRIVATE name = "debug_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "export_debug_port" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "use_generated_memory_model" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dedicated_memory_clk_phase_label" value="Dedicated memory clock phase:"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_clk_mhz" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "quartus_project_exists" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_if_drate" value="Half"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enable_v72_rsu" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_if_clk_mhz_label" value="(100.0 MHz)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "new_variant" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_memtype" value="DDR2 SDRAM"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pll_ref_clk_mhz" value="125.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_clk_ps_label" value="(5000 ps)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "family" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "project_family" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "speed_grade" value="4"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dedicated_memory_clk_phase" value="0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pll_ref_clk_ps_label" value="(8000 ps)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "avalon_burst_length" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WIDTH_RATIO" value="4"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_pchaddr_bit" value="10"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_clk_pair_count" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "vendor" value="Micron"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "chip_or_dimm" value="Discrete Device"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_fmax" value="333.333"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_cs_per_dimm" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pre_latency_label" value="Fix read latency at:"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dedicated_memory_clk_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_bankaddr_width" value="2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_preset_rlat" value="0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "post_latency_label" value="cycles (0 cycles=minimum latency, non-deterministic)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_dyn_deskew_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_cs_width" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_rowaddr_width" value="13"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_if_dwidth_label" value="32"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_dm_pins_en" value="Yes"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_preset" value="Custom (Micron MT47H64M8CB-3)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "fast_simulation_en" value="FAST"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_coladdr_width" value="10"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_dq_per_dqs" value="8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_dwidth" value="8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tiha_ps" value="400"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdsh_ck" value="0.2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_trfc_ns" value="105.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tqh_ck" value="0.36"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tisa_ps" value="400"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdss_ck" value="0.2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_tinit_us" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_trcd_ns" value="15.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_twtr_ck" value="3"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdqss_ck" value="0.25"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tqhs_ps" value="340"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdsa_ps" value="300"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tac_ps" value="450"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdha_ps" value="300"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_tras_ns" value="40.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_twr_ns" value="15.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdqsck_ps" value="400"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_trp_ns" value="15.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdqsq_ps" value="240"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_tmrd_ns" value="6.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_trefi_us" value="7.8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl" value="5.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_40_fmax" value="266.667"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_odt" value="50"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_dll_en" value="Yes"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ac_phase" value="240"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_drv_str" value="Normal"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_oct_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "input_period" value="0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_60_fmax" value="333.333"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "board_skew_ps" value="20"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_dqsn_en" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dll_external" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_15_fmax" value="533.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_30_fmax" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_bl" value="4"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ac_clk_select" value="dedicated"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_50_fmax" value="333.333"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_25_fmax" value="533.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_20_fmax" value="533.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pll_reconfig_ports_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_btype" value="Sequential"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ctl_ecc_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "user_refresh_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_if_type_avalon" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ctl_self_refresh_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ctl_autopch_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ctl_powerdn_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "tool_context" value="SOPC_BUILDER"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_srtr" value="Normal"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_mpr_loc" value="Predefined Pattern"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dss_tinit_rst_us" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_90_fmax" value="400.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_rtt_wr" value="Dynamic ODT off"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_100_fmax" value="400.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_pasr" value="Full Array"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_asrm" value="Manual SR Reference (SRT)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_mpr_oper" value="Predefined Pattern"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_80_fmax" value="400.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_drv_impedance" value="RZQ/7"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_rtt_nom" value="ODT Disabled"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_70_fmax" value="400.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_wtcl" value="5.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_dll_pch" value="Fast Exit"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_atcl" value="Disabled"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen">
-- Retrieval info:      <PRIVATE name = "use_alt_top" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "alt_top" value="ddr2_deva_auk_ddr_hp_controller_wrapper"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "nativelink_excludes" value="ddr2_deva_phy_alt_mem_phy_sequencer_wrapper.v,alt_mem_phy_sequencer.vhd,ddr2_deva_phy_alt_mem_phy_dss_wrapper.v,alt_mem_phy_dss.vhd,ddr2_deva_phy.vhd,ddr2_deva_phy_alt_mem_phy_siii.v,alt_mem_phy_defines.v"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "nativelink_includes" value="ddr2_deva_phy_alt_mem_phy_delay.vhd,ddr2_deva_phy.vho,ddr2_deva_phy_alt_mem_phy_sequencer_wrapper.vho"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "family" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "filename" value="ddr2_deva_auk_ddr_hp_controller_wrapper.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen2">
-- Retrieval info:      <PRIVATE name = "family" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "command" value="--simgen_arbitrary_blackbox=+ddr2_deva_phy_alt_mem_phy_delay;+ddr2_deva_alt_mem_phy_sequencer_wrapper;+ddr2_deva_alt_mem_phy_reconfig_siii;+ddr2_deva_alt_mem_phy_pll_siii --ini=simgen_tri_bus_opt=on"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "parameter" value="SIMGEN_INITIALIZATION_FILE=D:\sync\PhD\RangeImaging\Altera\PMD19k_Stratix3/ddr2_deva_simgen_init.txt"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen_enable">
-- Retrieval info:      <PRIVATE name = "language" value="vhdl"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enabled" value="0"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "qip">
-- Retrieval info:      <PRIVATE name = "gx_libs" value="1"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "greybox">
-- Retrieval info:      <PRIVATE name = "filename" value="ddr2_deva_gb.v"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "quartus_settings">
-- Retrieval info:      <PRIVATE name = "DEVICE" value="EP3SL150F1152C2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FAMILY" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "serializer"/>
-- Retrieval info:    </PRIVATES>
-- Retrieval info:    <FILES/>
-- Retrieval info:    <PORTS/>
-- Retrieval info:    <LIBRARIES/>
-- Retrieval info:   </STATIC_SECTION>
-- Retrieval info:  </NETLIST_SECTION>
-- Retrieval info: </MEGACORE>
-- =========================================================
