-- megafunction wizard: %altmemphy v8.0%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			ddr2_devb_phy_alt_mem_phy_siii
-- ============================================================
-- Generated by altmemphy 8.0 [Altera, IP Toolbench 1.3.0 Build 214]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2010 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;

ENTITY ddr2_devb_phy IS
	PORT (
		pll_ref_clk	: IN STD_LOGIC;
		global_reset_n	: IN STD_LOGIC;
		soft_reset_n	: IN STD_LOGIC;
		local_address	: IN STD_LOGIC_VECTOR (22 DOWNTO 0);
		local_read_req	: IN STD_LOGIC;
		local_wdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_write_req	: IN STD_LOGIC;
		local_size	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		local_be	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		local_refresh_req	: IN STD_LOGIC;
		local_burstbegin	: IN STD_LOGIC;
		ctl_ready	: IN STD_LOGIC;
		ctl_wdata_req	: IN STD_LOGIC;
		ctl_rdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		ctl_rdata_valid	: IN STD_LOGIC;
		ctl_refresh_ack	: IN STD_LOGIC;
		ctl_mem_addr_h	: IN STD_LOGIC_VECTOR (12 DOWNTO 0);
		ctl_mem_addr_l	: IN STD_LOGIC_VECTOR (12 DOWNTO 0);
		ctl_mem_ba_h	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		ctl_mem_ba_l	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		ctl_mem_cas_n_h	: IN STD_LOGIC;
		ctl_mem_cas_n_l	: IN STD_LOGIC;
		ctl_mem_cke_h	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_cke_l	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_cs_n_h	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_cs_n_l	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_odt_h	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_odt_l	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_ras_n_h	: IN STD_LOGIC;
		ctl_mem_ras_n_l	: IN STD_LOGIC;
		ctl_mem_we_n_h	: IN STD_LOGIC;
		ctl_mem_we_n_l	: IN STD_LOGIC;
		ctl_mem_be	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		ctl_mem_dqs_burst	: IN STD_LOGIC;
		ctl_mem_wdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		ctl_mem_wdata_valid	: IN STD_LOGIC;
		ctl_init_done	: IN STD_LOGIC;
		ctl_doing_rd	: IN STD_LOGIC;
		ctl_add_1t_ac_lat	: IN STD_LOGIC;
		ctl_add_1t_odt_lat	: IN STD_LOGIC;
		ctl_add_intermediate_regs	: IN STD_LOGIC;
		ctl_negedge_en	: IN STD_LOGIC;
		dqs_delay_ctrl_import	: IN STD_LOGIC_VECTOR (5 DOWNTO 0);
		pll_reconfig_enable	: IN STD_LOGIC;
		pll_reconfig_counter_type	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		pll_reconfig_counter_param	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		pll_reconfig_data_in	: IN STD_LOGIC_VECTOR (8 DOWNTO 0);
		pll_reconfig_read_param	: IN STD_LOGIC;
		pll_reconfig_write_param	: IN STD_LOGIC;
		pll_reconfig	: IN STD_LOGIC;
		oct_ctl_rs_value	: IN STD_LOGIC_VECTOR (13 DOWNTO 0);
		oct_ctl_rt_value	: IN STD_LOGIC_VECTOR (13 DOWNTO 0);
		local_autopch_req	: IN STD_LOGIC;
		local_powerdn_req	: IN STD_LOGIC;
		local_self_rfsh_req	: IN STD_LOGIC;
		ctl_self_rfsh_ack	: IN STD_LOGIC;
		ctl_powerdn_ack	: IN STD_LOGIC;
		reset_request_n	: OUT STD_LOGIC;
		phy_clk	: OUT STD_LOGIC;
		reset_phy_clk_n	: OUT STD_LOGIC;
		aux_half_rate_clk	: OUT STD_LOGIC;
		aux_full_rate_clk	: OUT STD_LOGIC;
		local_ready	: OUT STD_LOGIC;
		local_rdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_rdata_valid	: OUT STD_LOGIC;
		local_init_done	: OUT STD_LOGIC;
		local_refresh_ack	: OUT STD_LOGIC;
		local_wdata_req	: OUT STD_LOGIC;
		ctl_address	: OUT STD_LOGIC_VECTOR (22 DOWNTO 0);
		ctl_read_req	: OUT STD_LOGIC;
		ctl_wdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		ctl_write_req	: OUT STD_LOGIC;
		ctl_size	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_be	: OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
		ctl_refresh_req	: OUT STD_LOGIC;
		ctl_burstbegin	: OUT STD_LOGIC;
		ctl_mem_rdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		ctl_mem_rdata_valid	: OUT STD_LOGIC;
		ctl_rlat	: OUT STD_LOGIC_VECTOR (4 DOWNTO 0);
		ctl_usr_mode_rdy	: OUT STD_LOGIC;
		mem_addr	: OUT STD_LOGIC_VECTOR (12 DOWNTO 0);
		mem_ba	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		mem_cas_n	: OUT STD_LOGIC;
		mem_cke	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_cs_n	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dm	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_odt	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_ras_n	: OUT STD_LOGIC;
		mem_we_n	: OUT STD_LOGIC;
		mem_reset_n	: OUT STD_LOGIC;
		resynchronisation_successful	: OUT STD_LOGIC;
		postamble_successful	: OUT STD_LOGIC;
		tracking_successful	: OUT STD_LOGIC;
		tracking_adjustment_up	: OUT STD_LOGIC;
		tracking_adjustment_down	: OUT STD_LOGIC;
		dqs_delay_ctrl_export	: OUT STD_LOGIC_VECTOR (5 DOWNTO 0);
		dll_reference_clk	: OUT STD_LOGIC;
		pll_reconfig_clk	: OUT STD_LOGIC;
		pll_reconfig_reset	: OUT STD_LOGIC;
		pll_reconfig_data_out	: OUT STD_LOGIC_VECTOR (8 DOWNTO 0);
		pll_reconfig_busy	: OUT STD_LOGIC;
		local_self_rfsh_ack	: OUT STD_LOGIC;
		local_powerdn_ack	: OUT STD_LOGIC;
		ctl_autopch_req	: OUT STD_LOGIC;
		ctl_powerdn_req	: OUT STD_LOGIC;
		ctl_self_rfsh_req	: OUT STD_LOGIC;
		mem_clk	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_clk_n	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dq	: INOUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		mem_dqs	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dqsn	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0)
	);
END ddr2_devb_phy;

ARCHITECTURE SYN OF ddr2_devb_phy IS

	SIGNAL signal_wire0	:  STD_LOGIC_VECTOR (0 DOWNTO 0);
	SIGNAL signal_wire1	:  STD_LOGIC_VECTOR (0 DOWNTO 0);

	COMPONENT ddr2_devb_phy_alt_mem_phy_siii
	GENERIC (
		ADDR_CMD_2T_EN	: NATURAL;
		ADDR_CMD_ADD_1T	: STRING;
		ADDR_CMD_NEGEDGE_EN	: STRING;
		ADDR_COUNT_WIDTH	: NATURAL;
		CAPTURE_MIMIC_PATH	: NATURAL;
		CLOCK_INDEX_WIDTH	: NATURAL;
		DDR_MIMIC_PATH_EN	: NATURAL;
		DEDICATED_MEMORY_CLK_EN	: NATURAL;
		DLL_EXPORT_IMPORT	: STRING;
		DLL_DELAY_BUFFER_MODE	: STRING;
		DLL_DELAY_CHAIN_LENGTH	: NATURAL;
		DQS_OUT_MODE	: STRING;
		DQS_PHASE_SETTING	: NATURAL;
		DQS_PHASE	: NATURAL;
		DWIDTH_RATIO	: NATURAL;
		FAMILY	: STRING;
		MEM_TCL	: STRING;
		GENERATE_WRITE_DQS	: NATURAL;
		LOCAL_IF_CLK_PS	: NATURAL;
		LOCAL_IF_AWIDTH	: NATURAL;
		LOCAL_IF_BURST_LENGTH	: NATURAL;
		LOCAL_BURST_LEN_BITS	: NATURAL;
		LOCAL_IF_DWIDTH	: NATURAL;
		LOCAL_IF_DRATE	: STRING;
		LOCAL_IF_TYPE_AVALON_STR	: STRING;
		MEM_ADDR_CMD_BUS_COUNT	: NATURAL;
		MEM_IF_MEMTYPE	: STRING;
		MEM_IF_DWIDTH	: NATURAL;
		MEM_IF_BE_WIDTH	: NATURAL;
		MEM_IF_DQS_WIDTH	: NATURAL;
		MEM_IF_ROWADDR_WIDTH	: NATURAL;
		MEM_IF_BANKADDR_WIDTH	: NATURAL;
		MEM_IF_CS_WIDTH	: NATURAL;
		MEM_IF_DM_WIDTH	: NATURAL;
		MEM_IF_DM_PINS_EN	: NATURAL;
		MEM_IF_DQSN_EN	: NATURAL;
		MEM_IF_OCT_EN	: NATURAL;
		MEM_IF_DQ_PER_DQS	: NATURAL;
		MEM_IF_DQS_CAPTURE_EN	: NATURAL;
		MEM_IF_POSTAMBLE_EN_WIDTH	: NATURAL;
		MEM_IF_CLK_PAIR_COUNT	: NATURAL;
		MEM_IF_CLK_PS	: NATURAL;
		MIMIC_DEBUG_EN	: NATURAL;
		MIMIC_PATH_TRACKING_EN	: NATURAL;
		NUM_MIMIC_SAMPLE_CYCLES	: NATURAL;
		NUM_DEBUG_SAMPLES_TO_STORE	: NATURAL;
		ODT_ADD_1T	: STRING;
		PLL_EXPORT_IMPORT	: STRING;
		MEM_IF_CLK_PS_STR	: STRING;
		PLL_REF_CLK_PS	: NATURAL;
		PLL_STEPS_PER_CYCLE	: NATURAL;
		PLL_TYPE	: STRING;
		POSTAMBLE_INITIAL_LAT	: NATURAL;
		POSTAMBLE_AWIDTH	: NATURAL;
		POSTAMBLE_CALIBRATION_AND_SETUP_EN	: NATURAL;
		POSTAMBLE_HALFT_EN	: NATURAL;
		POSTAMBLE_RESYNC_LAT_CTL_EN	: NATURAL;
		RDP_INITIAL_LAT	: NATURAL;
		RDP_RESYNC_LAT_CTL_EN	: NATURAL;
		RESYNC_CALIBRATION_AND_SETUP_EN	: NATURAL;
		RESYNC_CALIBRATE_ONLY_ONE_BIT_EN	: NATURAL;
		RESYNC_PIPELINE_DEPTH	: NATURAL;
		READ_LAT_WIDTH	: NATURAL;
		TRAINING_DATA_WIDTH	: NATURAL;
		SCAN_CLK_DIVIDE_BY	: NATURAL;
		USE_MEM_CLK_FOR_ADDR_CMD_CLK	: NATURAL;
		ADDR_CMD_ADD_INTERMEDIATE_REGS	: STRING;
		QDRII_MEM_DLL_NUM_CLK_CYCLES	: NATURAL;
		PLL_RECONFIG_PORTS_EN	: NATURAL;
		REG_DIMM	: NATURAL
	);
	PORT (
		pll_ref_clk	: IN STD_LOGIC;
		global_reset_n	: IN STD_LOGIC;
		soft_reset_n	: IN STD_LOGIC;
		local_address	: IN STD_LOGIC_VECTOR (22 DOWNTO 0);
		local_read_req	: IN STD_LOGIC;
		local_wdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_write_req	: IN STD_LOGIC;
		local_size	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		local_be	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		local_refresh_req	: IN STD_LOGIC;
		local_burstbegin	: IN STD_LOGIC;
		ctl_ready	: IN STD_LOGIC;
		ctl_wdata_req	: IN STD_LOGIC;
		ctl_rdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		ctl_rdata_valid	: IN STD_LOGIC;
		ctl_refresh_ack	: IN STD_LOGIC;
		ctl_mem_addr_h	: IN STD_LOGIC_VECTOR (12 DOWNTO 0);
		ctl_mem_addr_l	: IN STD_LOGIC_VECTOR (12 DOWNTO 0);
		ctl_mem_ba_h	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		ctl_mem_ba_l	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		ctl_mem_cas_n_h	: IN STD_LOGIC;
		ctl_mem_cas_n_l	: IN STD_LOGIC;
		ctl_mem_cke_h	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_cke_l	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_cs_n_h	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_cs_n_l	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_odt_h	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_odt_l	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_ras_n_h	: IN STD_LOGIC;
		ctl_mem_ras_n_l	: IN STD_LOGIC;
		ctl_mem_we_n_h	: IN STD_LOGIC;
		ctl_mem_we_n_l	: IN STD_LOGIC;
		ctl_mem_be	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		ctl_mem_dqs_burst	: IN STD_LOGIC;
		ctl_mem_wdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		ctl_mem_wdata_valid	: IN STD_LOGIC;
		ctl_mem_wps_n	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_mem_rps_n	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_init_done	: IN STD_LOGIC;
		ctl_doing_rd	: IN STD_LOGIC;
		ctl_add_1t_ac_lat	: IN STD_LOGIC;
		ctl_add_1t_odt_lat	: IN STD_LOGIC;
		ctl_add_intermediate_regs	: IN STD_LOGIC;
		ctl_negedge_en	: IN STD_LOGIC;
		dqs_delay_ctrl_import	: IN STD_LOGIC_VECTOR (5 DOWNTO 0);
		pll_reconfig_enable	: IN STD_LOGIC;
		pll_reconfig_counter_type	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		pll_reconfig_counter_param	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		pll_reconfig_data_in	: IN STD_LOGIC_VECTOR (8 DOWNTO 0);
		pll_reconfig_read_param	: IN STD_LOGIC;
		pll_reconfig_write_param	: IN STD_LOGIC;
		pll_reconfig	: IN STD_LOGIC;
		oct_ctl_rs_value	: IN STD_LOGIC_VECTOR (13 DOWNTO 0);
		oct_ctl_rt_value	: IN STD_LOGIC_VECTOR (13 DOWNTO 0);
		local_autopch_req	: IN STD_LOGIC;
		local_powerdn_req	: IN STD_LOGIC;
		local_self_rfsh_req	: IN STD_LOGIC;
		ctl_self_rfsh_ack	: IN STD_LOGIC;
		ctl_powerdn_ack	: IN STD_LOGIC;
		reset_request_n	: OUT STD_LOGIC;
		phy_clk	: OUT STD_LOGIC;
		reset_phy_clk_n	: OUT STD_LOGIC;
		aux_half_rate_clk	: OUT STD_LOGIC;
		aux_full_rate_clk	: OUT STD_LOGIC;
		local_ready	: OUT STD_LOGIC;
		local_rdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_rdata_valid	: OUT STD_LOGIC;
		local_init_done	: OUT STD_LOGIC;
		local_refresh_ack	: OUT STD_LOGIC;
		local_wdata_req	: OUT STD_LOGIC;
		ctl_address	: OUT STD_LOGIC_VECTOR (22 DOWNTO 0);
		ctl_read_req	: OUT STD_LOGIC;
		ctl_wdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		ctl_write_req	: OUT STD_LOGIC;
		ctl_size	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		ctl_be	: OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
		ctl_refresh_req	: OUT STD_LOGIC;
		ctl_burstbegin	: OUT STD_LOGIC;
		ctl_mem_rdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		ctl_mem_rdata_valid	: OUT STD_LOGIC;
		ctl_rlat	: OUT STD_LOGIC_VECTOR (4 DOWNTO 0);
		ctl_usr_mode_rdy	: OUT STD_LOGIC;
		mem_addr	: OUT STD_LOGIC_VECTOR (12 DOWNTO 0);
		mem_ba	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		mem_cas_n	: OUT STD_LOGIC;
		mem_cke	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_cs_n	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_d	: OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		mem_dm	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_odt	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_ras_n	: OUT STD_LOGIC;
		mem_we_n	: OUT STD_LOGIC;
		mem_reset_n	: OUT STD_LOGIC;
		mem_doff_n	: OUT STD_LOGIC;
		mem_rps_n	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_wps_n	: OUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		resynchronisation_successful	: OUT STD_LOGIC;
		postamble_successful	: OUT STD_LOGIC;
		tracking_successful	: OUT STD_LOGIC;
		tracking_adjustment_up	: OUT STD_LOGIC;
		tracking_adjustment_down	: OUT STD_LOGIC;
		dqs_delay_ctrl_export	: OUT STD_LOGIC_VECTOR (5 DOWNTO 0);
		dll_reference_clk	: OUT STD_LOGIC;
		pll_reconfig_clk	: OUT STD_LOGIC;
		pll_reconfig_reset	: OUT STD_LOGIC;
		pll_reconfig_data_out	: OUT STD_LOGIC_VECTOR (8 DOWNTO 0);
		pll_reconfig_busy	: OUT STD_LOGIC;
		local_self_rfsh_ack	: OUT STD_LOGIC;
		local_powerdn_ack	: OUT STD_LOGIC;
		ctl_autopch_req	: OUT STD_LOGIC;
		ctl_powerdn_req	: OUT STD_LOGIC;
		ctl_self_rfsh_req	: OUT STD_LOGIC;
		mem_clk	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_clk_n	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dq	: INOUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		mem_dqs	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0);
		mem_dqsn	: INOUT STD_LOGIC_VECTOR (0 DOWNTO 0)
	);

	END COMPONENT;

BEGIN
	signal_wire0  <= (others => '0');
	signal_wire1  <= (others => '0');

	ddr2_devb_phy_alt_mem_phy_siii_inst : ddr2_devb_phy_alt_mem_phy_siii
	GENERIC MAP (
		ADDR_CMD_2T_EN => 1,
		ADDR_CMD_ADD_1T => "TRUE",
		ADDR_CMD_NEGEDGE_EN => "FALSE",
		ADDR_COUNT_WIDTH => 4,
		CAPTURE_MIMIC_PATH => 0,
		CLOCK_INDEX_WIDTH => 4,
		DDR_MIMIC_PATH_EN => 1,
		DEDICATED_MEMORY_CLK_EN => 0,
		DLL_EXPORT_IMPORT => "EXPORT",
		DLL_DELAY_BUFFER_MODE => "LOW",
		DLL_DELAY_CHAIN_LENGTH => 8,
		DQS_OUT_MODE => "DELAY_CHAIN2",
		DQS_PHASE_SETTING => 2,
		DQS_PHASE => 9000,
		DWIDTH_RATIO => 4,
		FAMILY => "Stratix III",
		MEM_TCL => "5.0",
		GENERATE_WRITE_DQS => 1,
		LOCAL_IF_CLK_PS => 10000,
		LOCAL_IF_AWIDTH => 23,
		LOCAL_IF_BURST_LENGTH => 1,
		LOCAL_BURST_LEN_BITS => 1,
		LOCAL_IF_DWIDTH => 32,
		LOCAL_IF_DRATE => "HALF",
		LOCAL_IF_TYPE_AVALON_STR => "true",
		MEM_ADDR_CMD_BUS_COUNT => 1,
		MEM_IF_MEMTYPE => "DDR2",
		MEM_IF_DWIDTH => 8,
		MEM_IF_BE_WIDTH => 4,
		MEM_IF_DQS_WIDTH => 1,
		MEM_IF_ROWADDR_WIDTH => 13,
		MEM_IF_BANKADDR_WIDTH => 2,
		MEM_IF_CS_WIDTH => 1,
		MEM_IF_DM_WIDTH => 1,
		MEM_IF_DM_PINS_EN => 1,
		MEM_IF_DQSN_EN => 1,
		MEM_IF_OCT_EN => 0,
		MEM_IF_DQ_PER_DQS => 8,
		MEM_IF_DQS_CAPTURE_EN => 1,
		MEM_IF_POSTAMBLE_EN_WIDTH => 1,
		MEM_IF_CLK_PAIR_COUNT => 1,
		MEM_IF_CLK_PS => 5000,
		MIMIC_DEBUG_EN => 0,
		MIMIC_PATH_TRACKING_EN => 1,
		NUM_MIMIC_SAMPLE_CYCLES => 6,
		NUM_DEBUG_SAMPLES_TO_STORE => 4096,
		ODT_ADD_1T => "FALSE",
		PLL_EXPORT_IMPORT => "NONE",
		MEM_IF_CLK_PS_STR => "5000 ps",
		PLL_REF_CLK_PS => 8000,
		PLL_STEPS_PER_CYCLE => 40,
		PLL_TYPE => "ENHANCED",
		POSTAMBLE_INITIAL_LAT => 13,
		POSTAMBLE_AWIDTH => 6,
		POSTAMBLE_CALIBRATION_AND_SETUP_EN => 1,
		POSTAMBLE_HALFT_EN => 0,
		POSTAMBLE_RESYNC_LAT_CTL_EN => 0,
		RDP_INITIAL_LAT => 6,
		RDP_RESYNC_LAT_CTL_EN => 0,
		RESYNC_CALIBRATION_AND_SETUP_EN => 1,
		RESYNC_CALIBRATE_ONLY_ONE_BIT_EN => 0,
		RESYNC_PIPELINE_DEPTH => 0,
		READ_LAT_WIDTH => 5,
		TRAINING_DATA_WIDTH => 32,
		SCAN_CLK_DIVIDE_BY => 2,
		USE_MEM_CLK_FOR_ADDR_CMD_CLK => 0,
		ADDR_CMD_ADD_INTERMEDIATE_REGS => "FALSE",
		QDRII_MEM_DLL_NUM_CLK_CYCLES => 2048,
		PLL_RECONFIG_PORTS_EN => 0,
		REG_DIMM => 0
	)
	PORT MAP (
		pll_ref_clk  =>  pll_ref_clk,
		global_reset_n  =>  global_reset_n,
		soft_reset_n  =>  soft_reset_n,
		reset_request_n  =>  reset_request_n,
		phy_clk  =>  phy_clk,
		reset_phy_clk_n  =>  reset_phy_clk_n,
		aux_half_rate_clk  =>  aux_half_rate_clk,
		aux_full_rate_clk  =>  aux_full_rate_clk,
		local_address  =>  local_address,
		local_read_req  =>  local_read_req,
		local_wdata  =>  local_wdata,
		local_write_req  =>  local_write_req,
		local_size  =>  local_size,
		local_be  =>  local_be,
		local_refresh_req  =>  local_refresh_req,
		local_burstbegin  =>  local_burstbegin,
		local_ready  =>  local_ready,
		local_rdata  =>  local_rdata,
		local_rdata_valid  =>  local_rdata_valid,
		local_init_done  =>  local_init_done,
		local_refresh_ack  =>  local_refresh_ack,
		local_wdata_req  =>  local_wdata_req,
		ctl_address  =>  ctl_address,
		ctl_read_req  =>  ctl_read_req,
		ctl_wdata  =>  ctl_wdata,
		ctl_write_req  =>  ctl_write_req,
		ctl_size  =>  ctl_size,
		ctl_be  =>  ctl_be,
		ctl_refresh_req  =>  ctl_refresh_req,
		ctl_burstbegin  =>  ctl_burstbegin,
		ctl_ready  =>  ctl_ready,
		ctl_wdata_req  =>  ctl_wdata_req,
		ctl_rdata  =>  ctl_rdata,
		ctl_rdata_valid  =>  ctl_rdata_valid,
		ctl_refresh_ack  =>  ctl_refresh_ack,
		ctl_mem_addr_h  =>  ctl_mem_addr_h,
		ctl_mem_addr_l  =>  ctl_mem_addr_l,
		ctl_mem_ba_h  =>  ctl_mem_ba_h,
		ctl_mem_ba_l  =>  ctl_mem_ba_l,
		ctl_mem_cas_n_h  =>  ctl_mem_cas_n_h,
		ctl_mem_cas_n_l  =>  ctl_mem_cas_n_l,
		ctl_mem_cke_h  =>  ctl_mem_cke_h,
		ctl_mem_cke_l  =>  ctl_mem_cke_l,
		ctl_mem_cs_n_h  =>  ctl_mem_cs_n_h,
		ctl_mem_cs_n_l  =>  ctl_mem_cs_n_l,
		ctl_mem_odt_h  =>  ctl_mem_odt_h,
		ctl_mem_odt_l  =>  ctl_mem_odt_l,
		ctl_mem_ras_n_h  =>  ctl_mem_ras_n_h,
		ctl_mem_ras_n_l  =>  ctl_mem_ras_n_l,
		ctl_mem_we_n_h  =>  ctl_mem_we_n_h,
		ctl_mem_we_n_l  =>  ctl_mem_we_n_l,
		ctl_mem_be  =>  ctl_mem_be,
		ctl_mem_dqs_burst  =>  ctl_mem_dqs_burst,
		ctl_mem_wdata  =>  ctl_mem_wdata,
		ctl_mem_wdata_valid  =>  ctl_mem_wdata_valid,
		ctl_mem_wps_n  =>  signal_wire0,
		ctl_mem_rps_n  =>  signal_wire1,
		ctl_mem_rdata  =>  ctl_mem_rdata,
		ctl_mem_rdata_valid  =>  ctl_mem_rdata_valid,
		ctl_rlat  =>  ctl_rlat,
		ctl_init_done  =>  ctl_init_done,
		ctl_doing_rd  =>  ctl_doing_rd,
		ctl_add_1t_ac_lat  =>  ctl_add_1t_ac_lat,
		ctl_add_1t_odt_lat  =>  ctl_add_1t_odt_lat,
		ctl_add_intermediate_regs  =>  ctl_add_intermediate_regs,
		ctl_negedge_en  =>  ctl_negedge_en,
		ctl_usr_mode_rdy  =>  ctl_usr_mode_rdy,
		mem_addr  =>  mem_addr,
		mem_ba  =>  mem_ba,
		mem_cas_n  =>  mem_cas_n,
		mem_cke  =>  mem_cke,
		mem_cs_n  =>  mem_cs_n,
		mem_d  =>  open,
		mem_dm  =>  mem_dm,
		mem_odt  =>  mem_odt,
		mem_ras_n  =>  mem_ras_n,
		mem_we_n  =>  mem_we_n,
		mem_reset_n  =>  mem_reset_n,
		mem_doff_n  =>  open,
		mem_rps_n  =>  open,
		mem_wps_n  =>  open,
		mem_clk  =>  mem_clk,
		mem_clk_n  =>  mem_clk_n,
		mem_dq  =>  mem_dq,
		mem_dqs  =>  mem_dqs,
		mem_dqsn  =>  mem_dqsn,
		resynchronisation_successful  =>  resynchronisation_successful,
		postamble_successful  =>  postamble_successful,
		tracking_successful  =>  tracking_successful,
		tracking_adjustment_up  =>  tracking_adjustment_up,
		tracking_adjustment_down  =>  tracking_adjustment_down,
		dqs_delay_ctrl_import  =>  dqs_delay_ctrl_import,
		dqs_delay_ctrl_export  =>  dqs_delay_ctrl_export,
		dll_reference_clk  =>  dll_reference_clk,
		pll_reconfig_enable  =>  pll_reconfig_enable,
		pll_reconfig_counter_type  =>  pll_reconfig_counter_type,
		pll_reconfig_counter_param  =>  pll_reconfig_counter_param,
		pll_reconfig_data_in  =>  pll_reconfig_data_in,
		pll_reconfig_read_param  =>  pll_reconfig_read_param,
		pll_reconfig_write_param  =>  pll_reconfig_write_param,
		pll_reconfig  =>  pll_reconfig,
		pll_reconfig_clk  =>  pll_reconfig_clk,
		pll_reconfig_reset  =>  pll_reconfig_reset,
		pll_reconfig_data_out  =>  pll_reconfig_data_out,
		pll_reconfig_busy  =>  pll_reconfig_busy,
		oct_ctl_rs_value  =>  oct_ctl_rs_value,
		oct_ctl_rt_value  =>  oct_ctl_rt_value,
		local_autopch_req  =>  local_autopch_req,
		local_powerdn_req  =>  local_powerdn_req,
		local_self_rfsh_req  =>  local_self_rfsh_req,
		local_self_rfsh_ack  =>  local_self_rfsh_ack,
		local_powerdn_ack  =>  local_powerdn_ack,
		ctl_autopch_req  =>  ctl_autopch_req,
		ctl_powerdn_req  =>  ctl_powerdn_req,
		ctl_self_rfsh_req  =>  ctl_self_rfsh_req,
		ctl_self_rfsh_ack  =>  ctl_self_rfsh_ack,
		ctl_powerdn_ack  =>  ctl_powerdn_ack
	);


END SYN;


-- =========================================================
-- altmemphy Wizard Data
-- ===============================
-- DO NOT EDIT FOLLOWING DATA
-- @Altera, IP Toolbench@
-- Warning: If you modify this section, altmemphy Wizard may not be able to reproduce your chosen configuration.
-- 
-- Retrieval info: <?xml version="1.0"?>
-- Retrieval info: <MEGACORE title="ALTMEMPHY"  version="8.0"  build="198"  iptb_version="1.3.0 Build 214"  format_version="120" >
-- Retrieval info:  <NETLIST_SECTION class="altera.ipbu.flowbase.netlist.model.DDRPHYMVCModel"  active_core="ddr2_devb_phy_alt_mem_phy_siii" >
-- Retrieval info:   <STATIC_SECTION>
-- Retrieval info:    <PRIVATES>
-- Retrieval info:     <NAMESPACE name = "parameterization">
-- Retrieval info:      <PRIVATE name = "debug_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "export_debug_port" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "use_generated_memory_model" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dedicated_memory_clk_phase_label" value="Dedicated memory clock phase:"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_clk_mhz" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "quartus_project_exists" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_if_drate" value="HALF"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enable_v72_rsu" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_if_clk_mhz_label" value="(100.0 MHz)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "new_variant" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_memtype" value="DDR2 SDRAM"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pll_ref_clk_mhz" value="125.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_clk_ps_label" value="(5000 ps)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "family" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "project_family" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "speed_grade" value="4"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dedicated_memory_clk_phase" value="0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pll_ref_clk_ps_label" value="(8000 ps)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "avalon_burst_length" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WIDTH_RATIO" value="4"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_pchaddr_bit" value="10"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_clk_pair_count" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "vendor" value="Micron"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "chip_or_dimm" value="Discrete Device"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_fmax" value="333.333"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_cs_per_dimm" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pre_latency_label" value="Fix read latency at:"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dedicated_memory_clk_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_bankaddr_width" value="2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_preset_rlat" value="0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "post_latency_label" value="cycles (0 cycles=minimum latency, non-deterministic)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_dyn_deskew_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_cs_width" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_rowaddr_width" value="13"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_if_dwidth_label" value="32"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_dm_pins_en" value="Yes"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_preset" value="Custom (Micron MT47H64M8CB-3)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "fast_simulation_en" value="FAST"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_coladdr_width" value="10"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_dq_per_dqs" value="8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_dwidth" value="8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tiha_ps" value="400"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdsh_ck" value="0.2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_trfc_ns" value="105.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tqh_ck" value="0.36"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tisa_ps" value="400"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdss_ck" value="0.2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_tinit_us" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_trcd_ns" value="15.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_twtr_ck" value="3"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdqss_ck" value="0.25"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tqhs_ps" value="340"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdsa_ps" value="300"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tac_ps" value="450"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdha_ps" value="300"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_tras_ns" value="40.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_twr_ns" value="15.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdqsck_ps" value="400"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_trp_ns" value="15.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tdqsq_ps" value="240"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_tmrd_ns" value="6.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_trefi_us" value="7.8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl" value="5.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_40_fmax" value="266.667"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_odt" value="50"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_dll_en" value="Yes"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ac_phase" value="240"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_drv_str" value="Normal"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_oct_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "input_period" value="0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_60_fmax" value="333.333"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "board_skew_ps" value="20"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_if_dqsn_en" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dll_external" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_15_fmax" value="533.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_30_fmax" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_bl" value="4"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ac_clk_select" value="dedicated"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_50_fmax" value="333.333"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_25_fmax" value="533.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_20_fmax" value="533.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pll_reconfig_ports_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_btype" value="Sequential"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ctl_ecc_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "user_refresh_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_if_type_avalon" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ctl_self_refresh_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ctl_autopch_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ctl_powerdn_en" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "tool_context" value="SOPC_BUILDER"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_srtr" value="Normal"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_mpr_loc" value="Predefined Pattern"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dss_tinit_rst_us" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_90_fmax" value="400.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_rtt_wr" value="Dynamic ODT off"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_100_fmax" value="400.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_pasr" value="Full Array"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_asrm" value="Manual SR Reference (SRT)"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_mpr_oper" value="Predefined Pattern"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_80_fmax" value="400.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_drv_impedance" value="RZQ/7"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_rtt_nom" value="ODT Disabled"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_tcl_70_fmax" value="400.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_wtcl" value="5.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_dll_pch" value="Fast Exit"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_atcl" value="Disabled"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen">
-- Retrieval info:      <PRIVATE name = "use_alt_top" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "alt_top" value="ddr2_devb_phy_alt_mem_phy_sequencer_wrapper"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "nativelink_includes" value="ddr2_devb_phy_alt_mem_phy_delay.vhd"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "family" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "filename" value="ddr2_devb_phy_alt_mem_phy_sequencer_wrapper.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen2">
-- Retrieval info:      <PRIVATE name = "family" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "command" value="--simgen_arbitrary_blackbox=+ddr2_devb_phy_alt_mem_phy_delay;+ddr2_devb_phy_alt_mem_phy_sequencer_wrapper;+ddr2_devb_phy_alt_mem_phy_reconfig_siii;+ddr2_devb_phy_alt_mem_phy_pll_siii --ini=simgen_tri_bus_opt=on"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "parameter" value="SIMGEN_INITIALIZATION_FILE=D:\sync\PhD\RangeImaging\Altera\PMD19k_Stratix3/ddr2_devb_phy_simgen_init.txt"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "filename" value="ddr2_devb_phy.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen_enable">
-- Retrieval info:      <PRIVATE name = "language" value="vhdl"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enabled" value="0"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "qip">
-- Retrieval info:      <PRIVATE name = "gx_libs" value="1"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "greybox">
-- Retrieval info:      <PRIVATE name = "filename" value="ddr2_devb_phy_gb.v"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "quartus_settings">
-- Retrieval info:      <PRIVATE name = "DEVICE" value="EP3SL150F1152C2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FAMILY" value="Stratix III"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "serializer"/>
-- Retrieval info:    </PRIVATES>
-- Retrieval info:    <FILES/>
-- Retrieval info:    <PORTS/>
-- Retrieval info:    <LIBRARIES/>
-- Retrieval info:   </STATIC_SECTION>
-- Retrieval info:  </NETLIST_SECTION>
-- Retrieval info: </MEGACORE>
-- =========================================================
