# TCL File Generated by Component Editor 8.0
# Thu Jan 15 11:08:29 NZDT 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dm9000a "DM9000A" v1.0.1
# | null 2009.01.15.11:08:29
# | 
# | 
# | D:/sync/PhD/altera_S3/PMD_Ranger_DE2/DM9000A/hdl/DM9000A_IF.v
# | 
# |    ./hdl/DM9000A_IF.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module dm9000a
# | 
set_module_property NAME dm9000a
set_module_property VERSION 1.0.1
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME DM9000A
set_module_property TOP_LEVEL_HDL_FILE hdl/DM9000A_IF.v
set_module_property TOP_LEVEL_HDL_MODULE DM9000A_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/DM9000A_IF.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ptfSchematicName ""

add_interface_port clk iCLK clk Input 1
add_interface_port clk iRST_N reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_export
# | 
add_interface avalon_slave_0_export conduit end

set_interface_property avalon_slave_0_export ASSOCIATED_CLOCK clk

add_interface_port avalon_slave_0_export iOSC_50 export Input 1
add_interface_port avalon_slave_0_export ENET_CMD export Output 1
add_interface_port avalon_slave_0_export ENET_RD_N export Output 1
add_interface_port avalon_slave_0_export ENET_WR_N export Output 1
add_interface_port avalon_slave_0_export ENET_CS_N export Output 1
add_interface_port avalon_slave_0_export ENET_RST_N export Output 1
add_interface_port avalon_slave_0_export ENET_CLK export Output 1
add_interface_port avalon_slave_0_export ENET_INT export Input 1
add_interface_port avalon_slave_0_export ENET_DATA export Bidir 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 minimumUninterruptedRunLength 1
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 addressSpan 2
set_interface_property avalon_slave_0 timingUnits Nanoseconds
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 writeWaitTime 40
set_interface_property avalon_slave_0 writeWaitStates 40
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 readWaitStates 40
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readWaitTime 40
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 printableDevice false

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clk

add_interface_port avalon_slave_0 iDATA writedata Input 16
add_interface_port avalon_slave_0 iCMD address Input 1
add_interface_port avalon_slave_0 iRD_N read_n Input 1
add_interface_port avalon_slave_0 iWR_N write_n Input 1
add_interface_port avalon_slave_0 iCS_N chipselect_n Input 1
add_interface_port avalon_slave_0 oDATA readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_irq
# | 
add_interface avalon_slave_0_irq interrupt end
set_interface_property avalon_slave_0_irq associatedAddressablePoint avalon_slave_0

set_interface_property avalon_slave_0_irq ASSOCIATED_CLOCK clk

add_interface_port avalon_slave_0_irq oINT irq Output 1
# | 
# +-----------------------------------
