# DM9000A Ethernet v3 Pins for HSMCB -> GPIO JP3 on Stratix III kit
set_location_assignment PIN_L5 -to ENET_CLK
set_location_assignment PIN_J6 -to ENET_CMD
set_location_assignment PIN_L4 -to ENET_CS_N
set_location_assignment PIN_K5 -to ENET_INT
set_location_assignment PIN_J7 -to ENET_RD_N
set_location_assignment PIN_K6 -to ENET_WR_N
set_location_assignment PIN_R12 -to ENET_DATA[0]
set_location_assignment PIN_N11 -to ENET_DATA[1]
set_location_assignment PIN_T11 -to ENET_DATA[2]
set_location_assignment PIN_N10 -to ENET_DATA[3]
set_location_assignment PIN_G2 -to ENET_DATA[4]
set_location_assignment PIN_H1 -to ENET_DATA[5]
set_location_assignment PIN_F1 -to ENET_DATA[6]
set_location_assignment PIN_H4 -to ENET_DATA[7]
set_location_assignment PIN_H6 -to ENET_DATA[8]
set_location_assignment PIN_H5 -to ENET_DATA[9]
set_location_assignment PIN_K8 -to ENET_DATA[10]
set_location_assignment PIN_L9 -to ENET_DATA[11]
set_location_assignment PIN_K7 -to ENET_DATA[12]
set_location_assignment PIN_L8 -to ENET_DATA[13]
set_location_assignment PIN_M10 -to ENET_DATA[14]
set_location_assignment PIN_M9 -to ENET_DATA[15]
set_location_assignment PIN_E1 -to debug[0]
set_location_assignment PIN_F3 -to debug[4]
