#
# Settings: ddr2 on the dimm 
# 
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[14]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_a[15]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_ba
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_casn
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_cke
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_cke[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_cke[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_clk_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_clk_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_clk_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_clk_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_clk_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_clk_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_csn
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_csn[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_csn[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dm[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[32]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[33]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[34]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[35]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[36]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[37]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[38]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[39]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[40]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[41]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[42]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[43]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[44]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[45]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[46]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[47]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[48]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[49]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[50]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[51]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[52]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[53]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[54]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[55]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[56]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[57]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[58]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[59]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[60]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[61]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[62]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[63]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[64]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[65]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[66]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[67]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[68]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[69]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[70]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dq[71]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_n[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS II" -to ddr2_dimm_dqs_p[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_odt
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_odt[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_odt[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_rasn
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_resetn
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_scl
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_sda
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_dimm_wen
set_location_assignment PIN_AG13 -to vref_dimm
set_location_assignment PIN_AM19 -to ddr2_dimm_a[0]
set_location_assignment PIN_AM18 -to ddr2_dimm_a[1]
set_location_assignment PIN_AF16 -to ddr2_dimm_a[2]
set_location_assignment PIN_AN16 -to ddr2_dimm_a[3]
set_location_assignment PIN_AM17 -to ddr2_dimm_a[4]
set_location_assignment PIN_AL19 -to ddr2_dimm_a[5]
set_location_assignment PIN_AK18 -to ddr2_dimm_a[6]
set_location_assignment PIN_AD16 -to ddr2_dimm_a[7]
set_location_assignment PIN_AE16 -to ddr2_dimm_a[8]
set_location_assignment PIN_AM16 -to ddr2_dimm_a[9]
set_location_assignment PIN_AH19 -to ddr2_dimm_a[10]
set_location_assignment PIN_AL16 -to ddr2_dimm_a[11]
set_location_assignment PIN_AF20 -to ddr2_dimm_a[12]
set_location_assignment PIN_AE23 -to ddr2_dimm_a[13]
set_location_assignment PIN_AG19 -to ddr2_dimm_a[14]
set_location_assignment PIN_AP12 -to ddr2_dimm_a[15]
set_location_assignment PIN_AN18 -to ddr2_dimm_ba[0]
set_location_assignment PIN_AL17 -to ddr2_dimm_ba[1]
set_location_assignment PIN_AD15 -to ddr2_dimm_ba[2]
set_location_assignment PIN_AD18 -to ddr2_dimm_casn
set_location_assignment PIN_AJ16 -to ddr2_dimm_cke[0]
set_location_assignment PIN_AP7 -to ddr2_dimm_cke[1]
set_location_assignment PIN_AM14 -to ddr2_dimm_clk_n[0]
set_location_assignment PIN_AL13 -to ddr2_dimm_clk_n[1]
set_location_assignment PIN_AM15 -to ddr2_dimm_clk_n[2]
set_location_assignment PIN_AL14 -to ddr2_dimm_clk_p[0]
set_location_assignment PIN_AK13 -to ddr2_dimm_clk_p[1]
set_location_assignment PIN_AL15 -to ddr2_dimm_clk_p[2]
set_location_assignment PIN_AG21 -to ddr2_dimm_csn[0]
set_location_assignment PIN_AC22 -to ddr2_dimm_csn[1]
set_location_assignment PIN_AL12 -to ddr2_dimm_dm[0]
set_location_assignment PIN_AP10 -to ddr2_dimm_dm[1]
set_location_assignment PIN_AJ15 -to ddr2_dimm_dm[2]
set_location_assignment PIN_AL22 -to ddr2_dimm_dm[3]
set_location_assignment PIN_AE22 -to ddr2_dimm_dm[4]
set_location_assignment PIN_AK27 -to ddr2_dimm_dm[5]
set_location_assignment PIN_AJ28 -to ddr2_dimm_dm[6]
set_location_assignment PIN_AP32 -to ddr2_dimm_dm[7]
set_location_assignment PIN_AH23 -to ddr2_dimm_dm[8]
set_location_assignment PIN_AP6 -to ddr2_dimm_dq[0]
set_location_assignment PIN_AN7 -to ddr2_dimm_dq[1]
set_location_assignment PIN_AK10 -to ddr2_dimm_dq[2]
set_location_assignment PIN_AK12 -to ddr2_dimm_dq[3]
set_location_assignment PIN_AM7 -to ddr2_dimm_dq[4]
set_location_assignment PIN_AM8 -to ddr2_dimm_dq[5]
set_location_assignment PIN_AM11 -to ddr2_dimm_dq[6]
set_location_assignment PIN_AP8 -to ddr2_dimm_dq[7]
set_location_assignment PIN_AE13 -to ddr2_dimm_dq[8]
set_location_assignment PIN_AF13 -to ddr2_dimm_dq[9]
set_location_assignment PIN_AP11 -to ddr2_dimm_dq[10]
set_location_assignment PIN_AF15 -to ddr2_dimm_dq[11]
set_location_assignment PIN_AE14 -to ddr2_dimm_dq[12]
set_location_assignment PIN_AE15 -to ddr2_dimm_dq[13]
set_location_assignment PIN_AP9 -to ddr2_dimm_dq[14]
set_location_assignment PIN_AN10 -to ddr2_dimm_dq[15]
set_location_assignment PIN_AN12 -to ddr2_dimm_dq[16]
set_location_assignment PIN_AM12 -to ddr2_dimm_dq[17]
set_location_assignment PIN_AG15 -to ddr2_dimm_dq[18]
set_location_assignment PIN_AH15 -to ddr2_dimm_dq[19]
set_location_assignment PIN_AN13 -to ddr2_dimm_dq[20]
set_location_assignment PIN_AP13 -to ddr2_dimm_dq[21]
set_location_assignment PIN_AP14 -to ddr2_dimm_dq[22]
set_location_assignment PIN_AK15 -to ddr2_dimm_dq[23]
set_location_assignment PIN_AJ21 -to ddr2_dimm_dq[24]
set_location_assignment PIN_AM22 -to ddr2_dimm_dq[25]
set_location_assignment PIN_AN21 -to ddr2_dimm_dq[26]
set_location_assignment PIN_AP21 -to ddr2_dimm_dq[27]
set_location_assignment PIN_AJ20 -to ddr2_dimm_dq[28]
set_location_assignment PIN_AK21 -to ddr2_dimm_dq[29]
set_location_assignment PIN_AP20 -to ddr2_dimm_dq[30]
set_location_assignment PIN_AM21 -to ddr2_dimm_dq[31]
set_location_assignment PIN_AE20 -to ddr2_dimm_dq[32]
set_location_assignment PIN_AF21 -to ddr2_dimm_dq[33]
set_location_assignment PIN_AP24 -to ddr2_dimm_dq[34]
set_location_assignment PIN_AP26 -to ddr2_dimm_dq[35]
set_location_assignment PIN_AD21 -to ddr2_dimm_dq[36]
set_location_assignment PIN_AE21 -to ddr2_dimm_dq[37]
set_location_assignment PIN_AP23 -to ddr2_dimm_dq[38]
set_location_assignment PIN_AN24 -to ddr2_dimm_dq[39]
set_location_assignment PIN_AP27 -to ddr2_dimm_dq[40]
set_location_assignment PIN_AN27 -to ddr2_dimm_dq[41]
set_location_assignment PIN_AL28 -to ddr2_dimm_dq[42]
set_location_assignment PIN_AK25 -to ddr2_dimm_dq[43]
set_location_assignment PIN_AM26 -to ddr2_dimm_dq[44]
set_location_assignment PIN_AL26 -to ddr2_dimm_dq[45]
set_location_assignment PIN_AP29 -to ddr2_dimm_dq[46]
set_location_assignment PIN_AM28 -to ddr2_dimm_dq[47]
set_location_assignment PIN_AN30 -to ddr2_dimm_dq[48]
set_location_assignment PIN_AM30 -to ddr2_dimm_dq[49]
set_location_assignment PIN_AJ26 -to ddr2_dimm_dq[50]
set_location_assignment PIN_AH27 -to ddr2_dimm_dq[51]
set_location_assignment PIN_AM29 -to ddr2_dimm_dq[52]
set_location_assignment PIN_AL29 -to ddr2_dimm_dq[53]
set_location_assignment PIN_AJ29 -to ddr2_dimm_dq[54]
set_location_assignment PIN_AJ27 -to ddr2_dimm_dq[55]
set_location_assignment PIN_AF24 -to ddr2_dimm_dq[56]
set_location_assignment PIN_AG24 -to ddr2_dimm_dq[57]
set_location_assignment PIN_AF23 -to ddr2_dimm_dq[58]
set_location_assignment PIN_AN31 -to ddr2_dimm_dq[59]
set_location_assignment PIN_AH25 -to ddr2_dimm_dq[60]
set_location_assignment PIN_AH26 -to ddr2_dimm_dq[61]
set_location_assignment PIN_AP31 -to ddr2_dimm_dq[62]
set_location_assignment PIN_AP30 -to ddr2_dimm_dq[63]
set_location_assignment PIN_AH22 -to ddr2_dimm_dq[64]
set_location_assignment PIN_AM23 -to ddr2_dimm_dq[65]
set_location_assignment PIN_AJ23 -to ddr2_dimm_dq[66]
set_location_assignment PIN_AJ24 -to ddr2_dimm_dq[67]
set_location_assignment PIN_AK22 -to ddr2_dimm_dq[68]
set_location_assignment PIN_AL23 -to ddr2_dimm_dq[69]
set_location_assignment PIN_AL25 -to ddr2_dimm_dq[70]
set_location_assignment PIN_AK24 -to ddr2_dimm_dq[71]
set_location_assignment PIN_AL11 -to ddr2_dimm_dqs_n[0]
set_location_assignment PIN_AN9 -to ddr2_dimm_dqs_n[1]
set_location_assignment PIN_AJ14 -to ddr2_dimm_dqs_n[2]
set_location_assignment PIN_AP22 -to ddr2_dimm_dqs_n[3]
set_location_assignment PIN_AP25 -to ddr2_dimm_dqs_n[4]
set_location_assignment PIN_AP28 -to ddr2_dimm_dqs_n[5]
set_location_assignment PIN_AM32 -to ddr2_dimm_dqs_n[6]
set_location_assignment PIN_AP33 -to ddr2_dimm_dqs_n[7]
set_location_assignment PIN_AM24 -to ddr2_dimm_dqs_n[8]
set_location_assignment PIN_AL10 -to ddr2_dimm_dqs_p[0]
set_location_assignment PIN_AM9 -to ddr2_dimm_dqs_p[1]
set_location_assignment PIN_AH14 -to ddr2_dimm_dqs_p[2]
set_location_assignment PIN_AN22 -to ddr2_dimm_dqs_p[3]
set_location_assignment PIN_AN25 -to ddr2_dimm_dqs_p[4]
set_location_assignment PIN_AN28 -to ddr2_dimm_dqs_p[5]
set_location_assignment PIN_AM31 -to ddr2_dimm_dqs_p[6]
set_location_assignment PIN_AN33 -to ddr2_dimm_dqs_p[7]
set_location_assignment PIN_AL24 -to ddr2_dimm_dqs_p[8]
set_location_assignment PIN_AE19 -to ddr2_dimm_odt[0]
set_location_assignment PIN_AD19 -to ddr2_dimm_odt[1]
set_location_assignment PIN_AN19 -to ddr2_dimm_rasn
set_location_assignment PIN_AE18 -to ddr2_dimm_resetn
set_location_assignment PIN_AN15 -to ddr2_dimm_scl
set_location_assignment PIN_AK19 -to ddr2_dimm_sda
set_location_assignment PIN_AJ19 -to ddr2_dimm_wen
#

