# DM9000A Ethernet v3 Pins for HSMCB -> GPIO JP3 on Stratix III kit
set_location_assignment PIN_AB6 -to ENET_CLK
set_location_assignment PIN_Y5 -to ENET_CMD
set_location_assignment PIN_AB5 -to ENET_CS_N
set_location_assignment PIN_AC7 -to ENET_INT
set_location_assignment PIN_Y6 -to ENET_RD_N
set_location_assignment PIN_AB8 -to ENET_WR_N
set_location_assignment PIN_W8 -to ENET_DATA[0]
set_location_assignment PIN_AA12 -to ENET_DATA[1]
set_location_assignment PIN_W7 -to ENET_DATA[2]
set_location_assignment PIN_AB11 -to ENET_DATA[3]
set_location_assignment PIN_AE2 -to ENET_DATA[4]
set_location_assignment PIN_AE1 -to ENET_DATA[5]
set_location_assignment PIN_AE4 -to ENET_DATA[6]
set_location_assignment PIN_AC2 -to ENET_DATA[7]
set_location_assignment PIN_AA7 -to ENET_DATA[8]
set_location_assignment PIN_AA6 -to ENET_DATA[9]
set_location_assignment PIN_Y8 -to ENET_DATA[10]
set_location_assignment PIN_Y10 -to ENET_DATA[11]
set_location_assignment PIN_Y7 -to ENET_DATA[12]
set_location_assignment PIN_Y9 -to ENET_DATA[13]
set_location_assignment PIN_W12 -to ENET_DATA[14]
set_location_assignment PIN_Y11 -to ENET_DATA[15]
set_location_assignment PIN_AC1 -to debug[0]
set_location_assignment PIN_Y3 -to debug[4]
