set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[18]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[0]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[1]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[2]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[3]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[4]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[5]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[6]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[7]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[8]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[9]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[10]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[11]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[12]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[13]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[14]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[15]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[16]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[17]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_addr[18]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[0]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[1]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[2]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[3]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[4]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[5]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[6]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[7]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[8]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[9]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[10]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[11]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[12]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[13]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[14]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[15]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[16]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_d[17]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[2]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[3]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[4]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[5]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[6]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[7]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[8]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[9]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[10]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[11]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[12]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[13]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[14]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[15]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[16]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_d[17]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[8]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[9]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[10]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[11]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[12]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[13]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[14]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[15]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[16]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_d[17]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dm[0]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dm[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dm[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dm[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_dm[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3151467 -to mem_dm[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_doff_n
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_doff_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_rps_n[0]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_rps_n[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_wps_n[0]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_wps_n[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V HSTL CLASS I" -to mem_clk[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITHOUT CALIBRATION" -to mem_clk[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V HSTL CLASS I" -to mem_clk_n[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITHOUT CALIBRATION" -to mem_clk_n[0]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[0]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[1]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[2]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[3]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[4]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[5]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[6]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[7]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[8]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[9]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[10]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[11]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[12]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[13]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[14]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[15]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[16]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dq[17]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[0]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[1]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[2]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[3]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[4]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[5]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[6]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[7]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[8]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[9]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[10]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[11]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[12]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[13]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[14]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[15]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[16]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dq[17]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_qvld
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dqs[0]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dqs[0]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to mem_dqsn[0]
set_instance_assignment -name IO_STANDARD "1.5-V HSTL CLASS I" -to mem_dqsn[0]
set_instance_assignment -name DQ_GROUP 18 -from mem_dqs[0] -to mem_dq[0..17]
set_instance_assignment -name DQ_GROUP 18 -from mem_clk[0] -to mem_d[0..17]
set_instance_assignment -name DQ_GROUP 18 -from mem_clk[0] -to mem_dm[0..1]
set_instance_assignment -name TREAT_BIDIR_AS_OUTPUT ON -to mem_clk[0]
set_instance_assignment -name TREAT_BIDIR_AS_OUTPUT ON -to mem_clk_n[0]
set_location_assignment PIN_C17 -to mem_addr[0]
set_location_assignment PIN_C14 -to mem_addr[1]
set_location_assignment PIN_C16 -to mem_addr[2]
set_location_assignment PIN_A14 -to mem_addr[3]
set_location_assignment PIN_A15 -to mem_addr[4]
set_location_assignment PIN_F14 -to mem_addr[5]
set_location_assignment PIN_F15 -to mem_addr[6]
set_location_assignment PIN_A13 -to mem_addr[7]
set_location_assignment PIN_J15 -to mem_addr[8]
set_location_assignment PIN_G16 -to mem_addr[9]
set_location_assignment PIN_E14 -to mem_addr[10]
set_location_assignment PIN_B14 -to mem_addr[11]
set_location_assignment PIN_J16 -to mem_addr[12]
set_location_assignment PIN_H16 -to mem_addr[13]
set_location_assignment PIN_F12 -to mem_addr[14]
set_location_assignment PIN_D14 -to mem_addr[15]
set_location_assignment PIN_A10 -to mem_addr[16]
set_location_assignment PIN_B13 -to mem_addr[17]
set_location_assignment PIN_C15 -to mem_addr[18]
set_location_assignment PIN_J14 -to mem_clk[0]
set_location_assignment PIN_H14 -to mem_clk_n[0]
set_location_assignment PIN_A9 -to mem_d[0]
set_location_assignment PIN_B10 -to mem_d[1]
set_location_assignment PIN_B11 -to mem_d[2]
set_location_assignment PIN_A11 -to mem_d[3]
set_location_assignment PIN_E11 -to mem_d[4]
set_location_assignment PIN_A12 -to mem_d[5]
set_location_assignment PIN_C12 -to mem_d[6]
set_location_assignment PIN_D12 -to mem_d[7]
set_location_assignment PIN_D13 -to mem_d[8]
set_location_assignment PIN_L14 -to mem_d[9]
set_location_assignment PIN_K15 -to mem_d[10]
set_location_assignment PIN_K13 -to mem_d[11]
set_location_assignment PIN_K14 -to mem_d[12]
set_location_assignment PIN_G13 -to mem_d[13]
set_location_assignment PIN_D10 -to mem_d[14]
set_location_assignment PIN_F11 -to mem_d[15]
set_location_assignment PIN_F13 -to mem_d[16]
set_location_assignment PIN_G12 -to mem_d[17]
set_location_assignment PIN_C11 -to mem_dm[0]
set_location_assignment PIN_D11 -to mem_dm[1]
set_location_assignment PIN_A3 -to mem_dq[0]
set_location_assignment PIN_B4 -to mem_dq[1]
set_location_assignment PIN_A4 -to mem_dq[2]
set_location_assignment PIN_A5 -to mem_dq[3]
set_location_assignment PIN_C6 -to mem_dq[4]
set_location_assignment PIN_F8 -to mem_dq[5]
set_location_assignment PIN_G9 -to mem_dq[6]
set_location_assignment PIN_F9 -to mem_dq[7]
set_location_assignment PIN_G10 -to mem_dq[8]
set_location_assignment PIN_J12 -to mem_dq[9]
set_location_assignment PIN_J11 -to mem_dq[10]
set_location_assignment PIN_G8 -to mem_dq[11]
set_location_assignment PIN_G11 -to mem_dq[12]
set_location_assignment PIN_B2 -to mem_dq[13]
set_location_assignment PIN_B5 -to mem_dq[14]
set_location_assignment PIN_F6 -to mem_dq[15]
set_location_assignment PIN_C5 -to mem_dq[16]
set_location_assignment PIN_D6 -to mem_dq[17]
set_location_assignment PIN_H11 -to mem_dqs[0]
set_location_assignment PIN_C4 -to mem_dqsn[0]
set_location_assignment PIN_D17 -to mem_rps_n[0]
set_location_assignment PIN_K16 -to mem_wps_n[0]
set_location_assignment PIN_A2 -to mem_qvld

